services:
  db:
    image: postgres:15
    container_name: odoo-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo-app
    environment:
      - GOOGLE_BOOKS_API_KEY=${GOOGLE_BOOKS_API_KEY}
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - "8069:8069"
    volumes:
      - ./custom_addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf
      - odoo_data:/var/lib/odoo

  #conectar external-api
  external-api:
    build:
      context: ./integrations/external_api
      dockerfile: Dockerfile
    container_name: external-api
    restart: unless-stopped
    ports:
      - "8000:8000"

volumes:
  postgres_data:
  odoo_data: