[options]
admin_passwd = $pbkdf2-sha512$600000$zNnb.7/3nnPOmdN6rxWCcA$ZOYuF2YjAS73VeiNeaIRYur3U5mKvlZffd4d3D6eqgesGGhzViaCEceXb.yfeneF3fL3Y48dOSq7vdrHCrIHEw
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
db_host = db
db_port = 5432
db_user = db_user_odoo
db_password = odoo_psw_db
log_level = info
data_dir = /var/lib/odoo
proxy_mode = True

